#!/bin/sh
STAGED=$(git diff --cached --name-only --diff-filter=ACM | grep '\.py$')
[ -z "$STAGED" ] && exit 0
uv run ruff check --fix -- $STAGED && uv run ruff format -- $STAGED
echo "$STAGED" | xargs git add
uv run ruff check . && uv run ruff format --check . && uv run ty check
